### ISSUE TITLE
Hot reload in modify the factory script section

### ISSUE THREAD

**Issue by Permagate** [defold/tutorial-side-scroller#2]
I went through side scroller tutorial until I arrived in section [Modify the factory script](https://github.com/defold/tutorial-side-scroller#modify-the-factory-script).

> Restart the game by closing the window (or press Escape – assuming you have enabled the "Escape Quits Game" option in File ▸ Preferences), then select Project ▸ Build from the editor menu.

Is there any particular reason why restarting the game is suggested here instead of hot reloading `factory.script`? I used hot reload and it generated the bonus star just fine.

I was thinking of making a PR to update that section to use hot reload, but there might be a good reason restarting game is written instead (especially since I'm new with Defold).

**Comment by britzl** [comment]
I think it makes sense to teach new users to use hot reload as much as possible.

**Comment by Permagate** [comment]
After going through the tutorial again, I think I'll not modify the part anymore. Because in the closing -> rebuild step, it introduces a new information (`Escape Quits Game` option).

> Restart the game by closing the window (or press Escape – assuming you have enabled the "Escape Quits Game" option in File ▸ Preferences), then select Project ▸ Build from the editor menu.
